#########################################################################################################
# kVisuals - The best(and probably the only one) alternative to ItemsAdder's ScreenEffects Addon!
# Encountered an issue?
# Join the discord server for support!
# https://starfal.net/discord
# Docs: https://wiki.starfal.net
#
# Made by kitoxis with love :)
#########################################################################################################

General:
  Language: en # Only english for now!
  Visuals: # You can enable and disable different visuals!
    Fullscreen: true
    Transparent: true
    Freezing: true
    Gradients:
      Fullscreen: true
      Bottom: true
      Top: true
      TopAndBottom: true
Permissions:
  General:
    ShowVisual: kvisuals.showvisual # The permission to show the visual
    Admin: kvisuals.admin # The permission for the admin command